[tasks.default]
alias = "custom-default"

[tasks.custom-default]
run_task = {name = ["build_armv6"]}

[tasks.build_armv6]
command = "cargo"
args = ["build", "--release", "--target", "arm-unknown-linux-gnueabihf"]
dependencies = ["build"]

[env]
PKG_CONFIG_ALLOW_CROSS="1"